send final result when stream is true
waylaidwanderer/node-chatgpt-api pull request #87
Opened 2023-02-16 17:24 UTC by likev

send final result(which contain important info such as conversationId) when stream is true

2023-02-17 00:20 UTC, waylaidwanderer commented on bin/server.js
> +            reply.sse({event:'RESULT', id: '', data: JSON.stringify(result) });
```suggestion
            reply.sse({ event: 'result', id: '', data: JSON.stringify(result) });
```

2023-02-17 00:21 UTC, waylaidwanderer commented
@likev could you also update the examples and readme too?

2023-02-17 03:14 UTC, likev commented
> uld you also update the examples and readme too?

@waylaidwanderer sure, i'll try my best

2023-02-17 13:31 UTC, likev commented
@waylaidwanderer Example and README.md of stream API are updated.

2023-02-18 20:31 UTC, waylaidwanderer requested changes

2023-02-18 20:31 UTC, waylaidwanderer commented on README.md
> +<summary><strong>Method1</strong></summary>
```suggestion
<summary><strong>Method 1</strong></summary>

```

2023-02-18 20:31 UTC, waylaidwanderer commented on README.md
> +<summary><strong>Method2</strong></summary>
```suggestion
<summary><strong>Method 2</strong></summary>

```

2023-02-18 20:31 UTC, waylaidwanderer commented on README.md
> +{ data: 'Object JSON', event: 'result', id: '', retry: undefined }
```suggestion
{ data: '<result JSON here>', event: 'result', id: '', retry: undefined }
```

2023-02-18 20:31 UTC, waylaidwanderer commented on README.md
> +- Method1 is simple but Time to First Byte (TTFB) is long.
```suggestion
- Method 1 is simple, but Time to First Byte (TTFB) is long.
```

2023-02-18 20:31 UTC, waylaidwanderer commented on README.md
> +- Method2 use non-standard implementation of [server-sent event API](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events), you should import `fetch-event-sour
```suggestion
- Method 2 uses a non-standard implementation of [server-sent event API](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events); you should import `fetch-event-source` first and use `POST` method.
```

2023-02-18 20:34 UTC, waylaidwanderer requested changes

2023-02-18 20:34 UTC, waylaidwanderer commented on README.md
> +<summary><strong>Method 1</strong></summary>
```suggestion
<summary><strong>Method 1 (POST)</strong></summary>
```

2023-02-18 20:34 UTC, waylaidwanderer commented on README.md
> +<summary><strong>Method 2</strong></summary>
```suggestion
<summary><strong>Method 2 (SSE)</strong></summary>
```

2023-02-18 20:34 UTC, waylaidwanderer approved these changes

2023-02-18 20:34 UTC, waylaidwanderer commented
@likev This is great, thanks so much.

2023-02-18 20:35 UTC, merged